##
## ui.R
##

source("libraries.R")

ui = tagList(
      navbarPage("",
      #theme = shinytheme("flatly"),
      #titlePanel("Advanced EDA by George Karapalidis", windowTitle = title),
      tabPanel("Google Analytics", icon = tags$i(class = "fas fa-signal"),
      #busyIndicator(text = h4("Extracting and processing data...", br(), br(), "This might take a while if Anti-sampling is ON.", style = "font-size: 18px;", img = "shinysky/busyIndicator/ajaxloaderq.gif", wait = 1000)),
      add_busy_bar(color = "#ffde25"),
      sidebarLayout(position = "right", fluid = FALSE,
             sidebarPanel(width = 3,
               div(googleAuth_jsUI("auth", login_text = "Authenticate with Google", logout_text = "Logout from Google", login_class = "btn btn-primary btn-sm", logout_class = "btn btn-danger btn-sm")),
               br(),
               h4("Select a Google ViewID"),
               authDropdownUI("auth_dropdown"),
               h4("Select your segment"),
               airDatepickerInput("datepicker", 
                                  label = "Date range", value = c(Sys.Date()-730, Sys.Date()-1), multiple = FALSE,
                                  range = TRUE, timepicker = FALSE,
                                  separator = " to ", placeholder = NULL,
                                  dateFormat = "dd-mm-yy",
                                  minDate = NULL, maxDate = NULL,
                                  disabledDates = NULL,
                                  view = c("days", "months", "years"),
                                  minView = c("days", "months", "years"),
                                  monthsField = c("monthsShort", "months"),
                                  clearButton = TRUE, todayButton = FALSE, autoClose = TRUE,
                                  timepickerOpts = timepickerOptions(),
                                  position = NULL, update_on = c("change", "close"),
                                  addon = c("none"),
                                  language = "en", inline = FALSE, width = "250px"
               ),
               prettyRadioButtons(inputId = "periodValue", "Period", 
                                  c("Day" = "day", "Week" = "week", "Month" = "month", "Annual" = "year"),
                                  inline = TRUE, animation = NULL, status = "info", thick = TRUE, bigger = TRUE
               ),
               selectInput("channel", "Channel",
                           c("All traffic" = "ga:medium=~.*",
                             "Organic Search" = "ga:medium==organic",
                             "Paid Search" = "ga:medium=~^(cpc|ppc)$",
                             "Other Advertising" = "ga:medium=~^(cpv|cpa|cpp|content-text|affiliate)$",
                             "Social" = "ga:medium=~^(social|social-network|social-media|sm|social network|social media)$;ga:hasSocialSourceReferral==Yes",
                             "Display" = "ga:medium=~^(display|cpm)$",
                             "Referral" = "ga:medium=~referral",
                             "Direct" = "ga:medium=~^\\(not set\\)|\\(none\\)$;ga:source==(direct)",
                             "Email" = "ga:medium=~email"
                           )
               ),
               textOutput("channelResult"),
               selectInput("metric", "Primary metric",
                           c("Sessions" = "sessions",
                             "Users" = "users",
                             "New Users" = "newUsers",
                             "Page Views" = "pageviews",
                             "Revenue" = "transactionRevenue",
                             "Transactions" = "transactions",
                             "All Goal Completions" = "goalCompletionsAll",
                             "Goal 1 Completions" = "goal1Completions",
                             "Goal 2 Completions" = "goal2Completions",
                             "Goal 3 Completions" = "goal3Completions",
                             "Goal 4 Completions" = "goal4Completions",
                             "Goal 5 Completions" = "goal5Completions",
                             "Goal 6 Completions" = "goal6Completions",
                             "Goal 7 Completions" = "goal7Completions",
                             "Goal 8 Completions" = "goal8Completions",
                             "Goal 9 Completions" = "goal9Completions",
                             "Goal 10 Completions" = "goal10Completions",
                             "Goal 11 Completions" = "goal11Completions",
                             "Goal 12 Completions" = "goal12Completions",
                             "Goal 13 Completions" = "goal13Completions",
                             "Goal 14 Completions" = "goal14Completions",
                             "Goal 15 Completions" = "goal15Completions",
                             "Goal 16 Completions" = "goal16Completions",
                             "Goal 17 Completions" = "goal17Completions",
                             "Goal 18 Completions" = "goal18Completions",
                             "Goal 19 Completions" = "goal19Completions",
                             "Goal 20 Completions" = "goal20Completions",
                             "totalEvents" = "totalEvents",
                             "uniqueEvents" = "uniqueEvents",
                             "eventValue" = "eventValue"
                           )
               ),
               textOutput("metricResult"),
               selectInput("secondaryMetric", "Secondary metric", selected = "transactions",
                           c("Sessions" = "sessions",
                             "Users" = "users",
                             "New Users" = "newUsers",
                             "Page Views" = "pageviews",
                             "Revenue" = "transactionRevenue",
                             "Transactions" = "transactions",
                             "All Goal Completions" = "goalCompletionsAll",
                             "Goal 1 Completions" = "goal1Completions",
                             "Goal 2 Completions" = "goal2Completions",
                             "Goal 3 Completions" = "goal3Completions",
                             "Goal 4 Completions" = "goal4Completions",
                             "Goal 5 Completions" = "goal5Completions",
                             "Goal 6 Completions" = "goal6Completions",
                             "Goal 7 Completions" = "goal7Completions",
                             "Goal 8 Completions" = "goal8Completions",
                             "Goal 9 Completions" = "goal9Completions",
                             "Goal 10 Completions" = "goal10Completions",
                             "Goal 11 Completions" = "goal11Completions",
                             "Goal 12 Completions" = "goal12Completions",
                             "Goal 13 Completions" = "goal13Completions",
                             "Goal 14 Completions" = "goal14Completions",
                             "Goal 15 Completions" = "goal15Completions",
                             "Goal 16 Completions" = "goal16Completions",
                             "Goal 17 Completions" = "goal17Completions",
                             "Goal 18 Completions" = "goal18Completions",
                             "Goal 19 Completions" = "goal19Completions",
                             "Goal 20 Completions" = "goal20Completions",
                             "totalEvents" = "totalEvents",
                             "uniqueEvents" = "uniqueEvents",
                             "eventValue" = "eventValue"
                           )
               ),
               textOutput("secondaryMetricResult"),
               prettyRadioButtons(inputId = "samplingValue", "Anti-sampling", 
                                      c("Off" = FALSE, "On" = TRUE),
                                      inline = TRUE, animation = NULL, status = "info", thick = TRUE, bigger = TRUE
                            ),
               #switchInput(label = "Anti-sampling", labelWidth = "120px", value = FALSE, inputId = "samplingValue", size = "default"),
               br(),
               div(style="display:center-align", downloadButton("downloadData", label = "Download datasets"))
             ),
             mainPanel(width = 9,
               h1("Advanced Website Performance Analysis", style="text-align:center"),
               h4("First, login to your Google account and select a ViewID.", style="text-align:center"),
               br(),
               tabsetPanel(
                 tabPanel(title=tagList(shiny::icon("tachometer"), "Performance"),
                          mainPanel(width = 12,
                                    column(width = 12, h3("Performance over time for primary metric", style="text-align:center")),
                                    column(width = 12, h5("Google updates are annotated for reference and analysis against performance.", style="text-align:center")),
                                    column(width = 12, br()),
                                    column(width = 12, dygraphOutput("sessions_plot", height = "300px")),
                                    column(width = 12, br()),
                                    column(width = 12, br()),
                                    column(width = 12, h3("Performance over time for secondary metric", style="text-align:center")),
                                    column(width = 12, h5("Google updates are annotated for reference and analysis against performance.", style="text-align:center")),
                                    column(width = 12, br()),
                                    column(width = 12, dygraphOutput("secondary_metric_plot", height = "300px")),
                                    # column(width = 12, br()),
                                    # column(width = 12, br()),
                                    # column(width = 12, h3("Relationship of primary and secondary metric", style="text-align:center")),
                                    # column(width = 12, h5("Analysis how positive is the relationship between the two metrics.", style="text-align:center")),
                                    # column(width = 12, br()),
                                    # column(width = 12, plotlyOutput("metric_scatter_plot", height = "300px")),
                                    column(width = 12, br()),  
                                    column(width = 12, br()),
                                    column(width = 12, h3("Performance by day of the week", style="text-align:center")),
                                    column(width = 12, h5("Analyse how the key metrics peform by week of year and day of the week.", style="text-align:center")),
                                    column(width = 12, br()),
                                    column(width = 1),
                                    column(width = 5, d3heatmapOutput("heatmap_primary_metric", height="800px", width = "100%")),
                                    column(width = 5, d3heatmapOutput("heatmap_secondary_metric", height="800px", width = "100%")),
                                    column(width = 1),
                                    column(width = 12, br())
                          )
                 ),
                 tabPanel(title=tagList(shiny::icon("sun"), "Seasonality"),
                          mainPanel(width = 12,
                                    column(width = 12, h3("Seasonality - Primary metric", style="text-align:center")),
                                    column(width = 12, h5("Identifying high and low activity periods during a calendar year.", p(), 
                                                          "Great for websites with multiple seasonal periods.", style="text-align:center")),
                                    column(width = 12, br()),
                                    column(width = 12, dygraphOutput("primary_metric_season_plot", height = "300px")),
                                    column(width = 12, br()),
                                    column(width = 12, br()),
                                    column(width = 12, h3("Seasonality - Secondary metric", style="text-align:center")),
                                    column(width = 12, br()),
                                    column(width = 12, dygraphOutput("secondary_metric_season_plot", height = "300px")),
                                    column(width = 12, br())
                                    
                          )
                 ),
                 tabPanel(title=tagList(shiny::icon("line-chart"), "Forecasting"),
                          mainPanel(width = 12,
                                    column(width = 12, h3("Forecasting - Primary metric", style="text-align:center")),
                                    column(width = 12, h5("For higher accuracy, select two or more years of data.", p(), 
                                                          "Adjust the forecasting period using the slider below.", style="text-align:center")),
                                    column(width = 12, br()),
                                    column(width = 12, dygraphOutput("forecast_plot", height = "300px")),
                                    column(width = 12, br()),
                                    column(width = 1),
                                    column(width = 10, br(),
                                                sliderInput("forecastPeriod", "Select focasting period",
                                                min = 10, max = 365,
                                                value = 60, step = 10, width = "100%", post = " days")),
                                    column(width = 1),
                                    column(width = 12, br()),
                                    column(width = 12, h3("Forecasting - Secondary metric", style="text-align:center")),
                                    column(width = 12, br()),
                                    column(width = 12, dygraphOutput("forecast_secondary_metric", height = "300px")),
                                    column(width = 12, br())
                                    
                          )
               ),
               tabPanel(title=tagList(shiny::icon("warning"), "Anomaly"),
                        mainPanel(width = 12,
                                  column(width = 12, h3("Anomaly Detection - Primary Metric", style="text-align:center")),
                                  column(width = 12, h5("Identifying dates with unsual activity.", style="text-align:center")),
                                  column(width = 12, br()),
                                  column(width = 12, dygraphOutput("anomaly_primary_metric_plot", height = "300px")),
                                  column(width = 12, br()),
                                  column(width = 12, br()),
                                  column(width = 1),
                                  column(width = 10, sliderInput("max_anoms", "Sensitivity",
                                                                 min = 0.0, max = 0.5,
                                                                 value = 0.05, step = 0.05, width = "100%")),
                                  column(width = 1),
                                  column(width = 12, br()),
                                  column(width = 12, h3("Anomaly Detection - Secondary Metric", style="text-align:center")),
                                  column(width = 12, h5("Identifying dates with unsual activity.", style="text-align:center")),
                                  column(width = 12, br()),
                                  column(width = 12, dygraphOutput("anomaly_secondary_metric_plot", height = "300px")),
                                  column(width = 12, br())
                        )
               ),
               tabPanel(title=tagList(shiny::icon("question-circle"), "Event"),
                        mainPanel(width = 12,
                                  column(width = 12, h3("Event Impact - Primary Metric", style="text-align:center")),
                                  column(width = 12, h5("Identifying events that had an impact on performance,", p(), 
                                                        " such as Google algorithmic updates or offline marketing.", style="text-align:center"))
                        )
               ),
               tabPanel(title=tagList(shiny::icon("cloud"), "Weather"),
                        mainPanel(width = 12,
                                  column(width = 12, h3("Weather Impact - Primary Metric", style="text-align:center")),
                                  column(width = 12, h5("Does weather have an impact to the performance of the website?", style="text-align:center"))
                        )
               )
             )
      )
    )
    ),
    tabPanel("Google Search Console", icon = tags$i(class = "fas fa-toolbox"),
              mainPanel(width = 12, h1("Coming soon...", style = "text-align:center"))
    ),
    tabPanel("SEO Causal Impact", icon = tags$i(class = "fas fa-search-location"),
             mainPanel(width = 12, h1("Coming soon...", style = "text-align:center"))
    ),
    tabPanel("Data Extraction", icon = tags$i(class = "fas fa-database"),
             mainPanel(width = 12, h1("Coming soon...", style = "text-align:center"))
    )
  ),

  tags$script(src = "https://karapalidis.com/wp-content/plugins/advanced-iframe/js/ai_external.js")
)
